@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-down-> "1" UniqueTeamList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person

Person -up-> "*" Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address

UniqueTeamList --> "~* all" Team
Team *--> Id
Team *--> TeamName
Team *--> LeaderId
Team *--> "*" Members
Team::west -> Team::west : " * SubTeams"
Team::east -> Team::east : "1 ParentTeam"
@enduml
